"use client";
import Head from "next/head";
import { Inter } from "next/font/google";
import React, { useState } from "react";
import { Button, Card, Error, Input, Pagination } from "@/src/components";
import home from "@/styles/pages/home.module.scss";
import useQueries from "@/src/hooks/useQueries";
import Loading from "@/src/components/loading";
import { usePathname } from "next/navigation";
import Link from "next/link";
const inter = Inter({ subsets: ["latin"] });
export default function Home() {
    const pathname = usePathname();
    const id = pathname.split("/").pop();
    const [page, setPage] = useState<number>(Number(id) || 1);
    const [search, setSearch] = useState("");
    const {
        data: movies,
        isLoading,
        isError,
    } = useQueries({
        main_key: `movie-list?page=${id}&items=20`,
        url: `movie-list?page=${id}&items=20`,
    });
    const handleChange = (e: any) => {
        setSearch(e.target.value);
    };
    if (isLoading) {
        return <Loading />;
    }
    if (isError) {
        return <Error message={"something error!"} />;
    }
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className={home.content}>
                <div className="container">
                    <Link href={"/"}>
                        <Button>go home</Button>
                    </Link>
                    <main className="flex justify-center">
                        <div className="w-5">
                            <Input
                                onChange={handleChange}
                                title={"Search"}
                                placeholder={"Enter movie name"}
                                type={"text"}
                            />
                        </div>
                    </main>
                    <div className="other flex justify-between flex-wrap py-3">
                        {!movies.data.movies ? (
                            <Error message={"something error!"} />
                        ) : (
                            movies.data.movies
                                ?.filter((item: any) =>
                                    item?.titleEn
                                        ? item?.titleEn
                                              .toLowerCase()
                                              .includes(search.toLowerCase())
                                        : item?.year
                                              .toString()
                                              .toLowerCase()
                                              .includes(search.toLowerCase())
                                )
                                .map((item: any) => {
                                    return (
                                        <Card
                                            id={item.id}
                                            key={item.id}
                                            url={item.poster}
                                            title={item.titleEn}
                                            year={item.year}
                                        />
                                    );
                                })
                        )}
                    </div>
                    <div className={"flex items-center justify-center p-1"}>
                        <Pagination
                            setPage={setPage}
                            page={page}
                            pageCount={movies?.data.lastPage}
                        />
                    </div>
                </div>
            </main>
        </>
    );
}
